import type { Metadata } from "next";
import "./globals.css";
import { poppins } from "../Public/fonts/fonts";
import Header from "./components/Header";
import { ClerkProvider } from "@clerk/nextjs";
import Footer from "./components/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang='en'>
        <body className={`${poppins.className} antialiased `}>
          <Header />
          {children}
          <Footer />
        </body>
      </html>
    </ClerkProvider>
  );
}
